import AppThemeContextProvider from '@/context/AppThemeContext'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <AppThemeContextProvider>
      <html lang="en">
        <body className='dark:bg-neutral-800 bg-white'>
          {children}
        </body>
      </html>
    </AppThemeContextProvider>
  )
}
